#!/bin/bash

plugins_dir=$(ls -A /plugins)
config_dir=$(ls  /etc/nagios/config.d)


for file in $config_dir;do

	if [ ! -f  /custom/$file ];then

	
	cp  /etc/nagios/config.d/$file /custom/$file

	fi

done


chown -R nagios.nagios /custom
chown -R nagios.nagios /plugins
chown -R nagios.nagios /etc/nagios/*
chown -R nagios.nagios /usr/lib/nagios/plugins/nsoporte
chmod +x /usr/lib/nagios/plugins/nsoporte/*


#Check Pid
if [ -d "/var/run/nagios"];then

	rm -rf /var/run/nagios
fi

mkdir /var/run/nagios
chown -R nagios.nagios /var/run/nagios	


if [ "$plugins_dir" != "" ];then

	chmod +x /plugins/*

fi


#Main Process 
exec /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f
